

package LexicalAnalyzer;

public class Token implements Cloneable {
	public String file = null;		// file name
	public int line = 0;			// line number
	public int column = 0;			// the column of the first character
	public String token = null;		// 
	public int type;				//  
	
	public boolean error = false;	// true means the token is generated by error recovery technique

	
    public Object clone(){
    	Token tk = null;
        try{
        	tk = (Token)super.clone();
        }catch(CloneNotSupportedException e){
            e.printStackTrace();
        }
        return tk;
    }
}
